team-moabam/moabam-FE

- .github/ISSUE_TEMPLATE/♻️-refactor.md
- .github/ISSUE_TEMPLATE/✨-feature.md
- .github/ISSUE_TEMPLATE/🚨-hotfix.md
- .github/workflows/pull_request.yml
- src/main.tsx
> chore: PR시 빌드하는 워크플로 작성

- .github/workflows/deploy.yml
- src/App.tsx
- src/main.tsx
- src/routes/router.tsx
- close #11 
- main 브랜치에 push 이벤트가 발생하면 빌드 후 S3 스토리지에 업로드하는 CI 스크립트를 작성했어요.
- 라우터 import 설정을 `main.ts` 가 아닌 `App` 컴포넌트에서 하도록 수정했어요.
> chore: 배포 CI 스크립트 작성

- src/App.tsx
- src/core/routes/router.tsx
- src/main.css
- src/main.tsx
- close #45
- 페이지 레이아웃을 작성했습니다.
- max-w-md 적용
- Outlet 에만 스크롤 발생하도록 작성
- Outlet 높이 최대로 늘어나게 작성
- 다크모드 / 라이트모드에 따른 배경색상, 글자색상 추가
- 페이지 라우트를 연결할 때 '/' 경로의 children 으로 넣어주어야 합니다
- Navbar 는 App.js에서 Outlet 밖에 임시로 넣어놨습니다! 공통 컴포넌트로 교체해야 합니다!
> feat: 페이지 레이아웃 작성

- src/shared/RoutineList/RoutineList.stories.tsx
- src/shared/RoutineList/components/RoutineItem.tsx
- src/shared/RoutineList/components/RoutineList.tsx
- src/shared/RoutineList/index.ts
- close #49
- 루틴 리스트 컴포넌트를 작성했습니다.
```tsx
<RoutineList>
<RoutineItem>밥 먹기</RoutineItem>
<RoutineItem
contents="세수 하기"
completed
/>
<RoutineItem contents="책 읽기" />
</RoutineList>
```
- RoutineList, RoutineItem 을 import 해서 사용합니다.
- 사용 방법은 html 기본 태그인 ul, li 와 동일합니다.
- 루틴 완료된 RoutineItem 의 경우, completed 를 넣어 UI 에 완료를 표시할 수 있습니다.
- 루틴 내용을 설정하는 방법은 두 가지 입니다. (편한 방법 사용하세요!)
- contents prop 으로 전달 : `<RoutineItem contents="책 읽기" />`
- children 으로 전달 : `<RoutineItem>책 읽기</RoutineItem>`
- 이 외에도, 커스텀 스타일로 덮고 싶은 경우 RoutineList 에게 className 을 부여할 수 있습니다.
> feat: RoutineList 컴포넌트 작성

- .storybook/preview-body.html
- index.html
- src/App.tsx
- src/core/constants/portals.ts
- src/core/hooks/useTheme.stories.tsx
- src/core/hooks/useTheme.tsx
- src/main.css
- src/main.tsx
- close #57 
- **시간 기반으로 테마를 설정하는 기능은 작업하지 못했습니다.**
- 구현 단계에는 테스트를 위해서 토글 기능을 넣어 놓는게 더 편할 거라고 생각했어요!
- `useTheme` 은 앱 전역에서 현재 UI의 테마에 대한 정보를 가져올 수 있는 훅이에요.
- `main.tsx` 에 기본적으로 `ThemeProvider` 로 감싸져 있고, `App 컴포넌트` 의 최상위 노드에 테마에 따른 `className` 이 부여되어 있어요.
- 따라서, 일반적으로는 `useTheme` 에서 테마를 꺼내지 않아도 각 요소의 클래스 네임에 테마마다 원하는 스타일을 지정해주면 돼요.
> 다만, createPortal() 을 이용한 경우에는 그 컴포넌트에서 `useTheme` 훅을 통해서 테마에 대한 정보를 최상위 노드의 클래스 네임에 부여해줘야 해요.
```tsx
const NormalPage = () => {
return (
<div>
<div className="dark:bg-black dark:text-white">하이</div>
</div>
);
};
```
```tsx
const PortalPage = () => {
const { theme } = useTheme();
return (
<>
{createPortal(
<div className={theme === 'dark' ? 'dark' : ''}> // 이렇게 최상위 노드에서 테마 클래스 지정이 필요해요.
<div className="h-full overflow-auto bg-light-main text-black …
```
> feat: ThemeContext 작성

- src/App.tsx
- src/main.css
- src/shared/BottomSheet/components/BottomSheet.tsx
- tailwind.config.js
- close #80
- BottomSheet 의 `width` 가 스크린 사이즈에 의존하던 문제 수정
- BottomSheet 와 Toast 에서 사용되는 `z-index` 속성을 테일윈드 설정에 추가
- 앱 화면의 사이즈를 표현하는 `app-container` 클래스 정의
- 폰트를 지정하는 중복 코드 제거
https://github.com/team-moabam/moabam-FE/assets/50488780/c920baa8-8c58-4fa4-84fe-8df497fcbe04
> fix: BottomSheet의 width 및 z-index 문제 수정

- src/shared/LoadingSpinner/components/LoadingSpinner.stories.tsx
- src/shared/LoadingSpinner/components/LoadingSpinner.tsx
- src/shared/LoadingSpinner/index.ts
- close #105 
로딩 UI를 나타낼 수 있는 스피너 컴포넌트를 만들었어요.
> feat: LoadingSpinner 컴포넌트 작성

- .github/workflows/pull_request.yml
- close #112
- React, Storybook 의 빌드를 각각 다른 job에서 수행하도록 수정
> chore: 빌드 테스트 CI 속도 개선

- src/RoomNew/components/Navbar.tsx
- src/RoomSetting/index.ts
- src/RoomSetting/tabs/MemberTab.tsx
- src/RoomSetting/tabs/RemoveTab.tsx
- src/RoomSetting/tabs/RoomTab.tsx
- src/core/routes/routes.tsx
- src/pages/RoomNewPage.tsx
- src/pages/RoomSetting.tsx
- src/pages/RoomSettingPage.tsx
> feat: 방 관리 페이지 UI 작성

- src/StartSlide/components/Background.tsx
- src/StartSlide/components/Star.tsx
- src/StartSlide/components/SwipeArrow.tsx
- src/StartSlide/components/UserBird.tsx
- src/StartSlide/components/UserInfo.tsx
- src/StartSlide/constants/contents.ts
- src/StartSlide/hooks/useRandomMessage.ts
- src/StartSlide/styles/swipeArrow.css
- src/StartSlide/utils/getRandomValue.ts
- src/pages/StartPage.tsx
- src/shared/Icon/constants/icons.ts
- close #131
* 시작페이지 > 루틴페이지 페이지 전환을 구현했습니다
* 잠금화면처럼 스와이프로 작동하게 했습니다
* 새 클릭 시, 랜덤 메시지가 출력되는 기능을 구현했습니다
https://github.com/team-moabam/moabam-FE/assets/62418379/9b174384-5c24-4626-b89c-6fa3fe6e69d3
> feat: 시작페이지 트랜지션 구현

- src/core/api/instance.ts
- src/core/api/types.ts
- close #150 
- 배열 형태의 데이터를 파싱할 때 발생하는 문제가 있어서 statusCode 파싱 로직을 제거했어요.
확인 후 바로 머지해주셔도 좋습니다!!
> fix: statusCode 파싱 로직 제거

- .github/workflows/deploy.yml
- close #171
- 추가된 `env` 내용을 배포 CI 스크립트에 추가
> chore: 배포시 env 내용 추가

- .github/workflows/deploy.yml
- close #175 
- 배포 S3 버킷 이름 변경
> chore: 배포 S3 버킷 이름 변경

- src/core/api/instance.ts
- close #179 
- withCredentials 추가
> fix: withCredentials 추가

- .github/workflows/deploy.yml
- close #204 
- 배포 CI 스크립트의 .env 내용에 누락된 VITE_FIREBASE_API_KEY 추가
> fix: VITE_FIREBASE_API_KEY 추가

- src/RoomSearch/components/Selection.tsx
- src/core/api/functions/roomAPI.ts
- src/core/api/queries/useSearchRooms.ts
- src/core/types/TotalRooms.ts
- src/pages/SearchPage.tsx
- close #210
요청 타입과 params 를 수정했습니다
> fix: 방 전체 조회 및 검색 기능 요청 params 수정

- .github/workflows/deploy.yml
- src/core/api/functions/notificationAPI.ts
- close #215
- FCM 토큰 API 호출 오류 수정
> fix: FCM 토큰 API 호출 오류 수정

- src/pages/RoomDetailPage.tsx
- close #230 
[모아밤.webm](https://github.com/team-moabam/moabam-FE/assets/65156388/7595e937-4a11-4792-8368-7d1c172c477a)
링크가 공유되면, 사용자가 이 링크를 타고 들어옵니다. 이때 로그인이 필요한 사항이라면 로그인으로 리다이랙트 될 것이예요
로그인을 한 후 다시 공유되었던 링크로 돌아와야합니다.
> feat: 공유 버튼 기능 추가

- src/core/api/queryClient.ts
- close #249 
- CORS 이슈의 해결로 기존의 임시 코드를 제거했어요.
> fix: 로그인 리다이렉션에 error.code 체크 로직 제거

- src/PWAInstallBanner/components/PWAInstallBanner.tsx
- src/PWAInstallBanner/hooks/usePWAInstallBanner.tsx
- src/main.tsx
- close #253 
- PWA 배너 관련 상태를 context로 관리
- setupMSW, setupFCM을 비동기적으로 처리
> fix: PWA 배너가 리렌더링시 사라지는 오류 수정

- src/RoomSlide/components/SlideController.tsx
- src/pages/RoutinesPage.tsx
- close #257
루틴 페이지의 슬라이더 버튼을 수정했습니다
사실 크게 변한건 없습니다 .. ! 버튼을 움직일 때 마다 가운데가 갈라지는 것처럼 보이길래 그 부분만 수정했어요
> feat: 루틴페이지 슬라이더 버튼 수정

- index.html
- src/main.css
- close #259
- body, app-container height 값 수정
- maximum-scale = 1 추가 
https://github.com/team-moabam/moabam-FE/assets/62418379/de262e0d-a40d-46e1-96ae-625e2ff9e113
https://github.com/team-moabam/moabam-FE/assets/62418379/179b6515-8200-415d-b9e1-b50179f569ca
https://github.com/team-moabam/moabam-FE/assets/62418379/b1f48eec-b528-4869-9afa-4cb24b2bdbed
- 모바일 검색 아코디언 친구들이 너무 버벅여서 개선하려는 시도를 해봤는데 .. 잘 안되는군요 ㅠㅠ
- 추가로, 하단에 input 있을 때 알아서 브라우저가 화면을 밀어주더라고요 ?!  이 부분은 특별히 조치를 안취해도 될듯합니다
> feat: 모바일 브라우저 UI 문제 해결

- src/pages/JoinPage.tsx
- src/pages/NotFoundPage.tsx
- src/pages/RankPage.tsx
- close #267
100% 로 높이 수정 했습니다
> fix: 랭크, 조인, 404 높이 수정 

- src/RoomSummary/components/RoomSummary.tsx
- close #282
RoomSummary 컴포넌트 (루틴페이지, 검색페이지에 쓰임) 
새 이미지 뒤의 배경 색상을 수정했습니다
> feat: RoomSummary 컴포넌트 새 배경 색상 수정

- src/RoomDetail/utils/makeWeekCalendar.ts
> fix: 캘린더 일요일 관련 오류 수정

- src/RoomDetail/components/RoomPreview.tsx
- close #295 
방 참여시 비밀번호 있으면 비밀번호 인풋이 보이고, 비밀번확 없으면 비밀번호 인풋이 사라집니다
> feat: 방 참여시 비밀번호 확인

- src/RoomDetail/components/RoomPreview.tsx
- close #298 
checkRoomJoin API에 대한 키 수정
> fix: checkRoomJoin API에 대한 키 수정

- src/App.tsx
- src/Meta/components/CommonMeta.tsx
- src/Meta/components/RoomDetailMeta.tsx
- src/shared/Header/components/Header.tsx
- close #296
- 오픈그래프 수정
- 헤더 컴포넌트 수정 (prev = -1 하면 됨)
> fix: 오픈그래프 오류 수정 및 헤더 컴포넌트 수정

- src/RoomDetail/components/RoomPreview.tsx
- close #298 
fix: check room join API reload
> fix: check room join API reload

- src/RoomDetail/components/RoomPreview.tsx
- src/core/api/functions/roomAPI.ts
- close #298 
방 참가 시 joinRoom API 요청
> fix: 방 참가 시 joinRoom API 요청

- src/RoomDetail/components/RoomDetail.tsx
- src/RoomDetail/components/RoomHeader.tsx
> feat: 방장만 수정 버튼 보이기

- src/main.tsx
- close #316
- 리소스 요청에 무의미한 MSW Warning 메시지를 출력하지 않도록 필터 조건을 걸었어요.
(https://mswjs.io/docs/api/setup-worker/start/#onunhandledrequest)
> chore: MSW 경고 문구 출력에 필터 조건 추가

- src/Promotion/components/EventCard.tsx
- src/Promotion/components/EventList.tsx
- close #309
- 백엔드에서 논의된 대로, 쿠폰발급 버튼을 누를 시 나타나는 토스트를 변경했습니다.
- 쿠폰이 아무것도 없을 경우, 안내하는 텍스트를 추가했습니다
> feat: 이벤트 페이지 UI 수정 (발급 토스트)

- index.html
- src/Meta/components/CommonMeta.tsx
- src/Meta/components/RoomDetailMeta.tsx
- close #320
opengraph 작성 정적파일로 이사 (index.html)
Meta 컴포넌트들 title 만 바뀌게 수정
배포 후 테스트를 하기 위해 빠른 머지 하겠습니닷...!!
> feat: opengraph 작성 수정

- index.html
- close #320
og:url 을 수정해봤습니다
현재는 카카오톡에서만 잘 나옵니다..!
> fix: opengraph og:url 수정

- src/RoomDetail/components/RoomDetail.tsx
- src/RoomDetail/components/RoomPreview.tsx
- src/RoomDetail/components/RoomSemi.tsx
- src/core/mocks/handlers/rooms.ts
- src/pages/RoomDetailPage.tsx
- #324 
- 에러 메세지 추가
- 에러 토스트 추가
> feat: input 에러메세지 추가

- src/RoomDetail/components/RoomMembers.tsx
- src/shared/Avatar/Avatar.tsx
> fix: 멤버 관련 로직 수정

- src/RoomDetail/components/RoomNotice.tsx
- close #326 
공지사항 내용이 없을 때는 안보이게 처리했습니다
> refactor : 공지 UI 수정

- src/RoomDetail/components/ReportBottomSheet.tsx
- src/RoomDetail/components/RoomHeader.tsx
- src/RoomDetail/components/RoomMembers.tsx
- src/RoomDetail/components/RoomWorkspace.tsx
- src/RoomSetting/tabs/MemberTab/DelegationButton.tsx
- src/RoomSetting/tabs/MemberTab/KickButton.tsx
- src/RoomSetting/tabs/MemberTab/index.tsx
- src/core/api/functions/notificationAPI.ts
- src/core/api/functions/roomAPI.ts
- src/core/types/Member.ts
- src/core/types/Reports.ts
- src/shared/Avatar/Avatar.stories.ts
- src/shared/Avatar/Avatar.tsx
- close #330
memberId가 string이여서 발생하는 오류들이 있었습니다.
원래 memberId 타입 number로 바꿔놨습니다!
> fix: memberId 타입 number로 변경

- src/RoomDetail/components/RoomHeader.tsx
- src/RoomDetail/components/RoomPreview.tsx
- 방 가입시 토스트 에러 띄우기
- 테스트용 콘솔 작성
> fix: 방 상세 페이지 오류 수정

- src/MyBird/components/HeaderWallet.tsx
- src/MyBird/components/ProductSheet.tsx
- src/OrderLogList/components/OrderLogList.tsx
- src/UserProfile/components/UserMain.tsx
- src/UserProfile/components/UserProfile.tsx
- src/core/mocks/datas/bugHistory.ts
- src/core/mocks/datas/member.ts
- src/core/types/BugHistory.ts
- src/core/types/Member.ts
- src/pages/OrderLogPage.tsx
- close #322
피드백 1차 적용입니다.
마이페이지 한줄 소개 플레이스홀터추가 = 추가했습니다. ps. 닉네임이 '' 일 경우는 없기에 추가 안했습니다.
마이페이지 새 = 패딩 색깔 적용했습니다.
마이페이지 뱃지 = 이제 이름 나옵니다. 아이콘 뭐로 할지는 딱 정해놓고 할게요
새 스킨 변경 지갑 안 보임 = 유저페이지 api 변경된거 적용 안된거였습니다 수정했습니다
희빈님:
사용내역(구매내역) 버그 고쳤습니다
사용내역에서 구매내역으로 변경했습니다.
사용내용이 없을시 다른거 보여주는거는.. 이거 적용하면 다른 곳도 다 넣어야해서 다른 이슈로 뺼게요
> feat: 마이, 상점 피드백 1차 적용

- src/RoomDetail/components/RoomDetail.tsx
- src/RoomDetail/components/RoomHeader.tsx
- src/core/mocks/datas/room.ts
- src/core/types/Room.ts
- close #333 
- 
nickname 변수명 수정
> fix: managerNickname 변수명 수정

- .env.example
- .github/workflows/deploy.yml
- close #343 
- 배포 env에 토스페이먼츠 추가
> chore: 배포 env에 토스페이먼츠 추가

- src/RoomSetting/tabs/RoomTab.tsx
- src/pages/RoomNewPage.tsx
- src/pages/RoomSettingPage.tsx
- close #334 
- 방 관리 페이지 404 응답시 NotFound 렌더링 (권한 없는 경우)
> fix: 방 관리 페이지 404 응답시 NotFound 렌더링

- src/RoomDetail/components/ReportBottomSheet.tsx
- src/RoomDetail/components/RoomMember.tsx
- src/RoomDetail/components/RoomMembers.tsx
- src/RoomDetail/components/RoomRoutine.tsx
- src/RoomDetail/components/RoomWorkspace.tsx
- src/RoomDetail/constants/constant.ts
- src/core/types/Reports.ts
- src/shared/Toast/components/ToastManager.tsx
> fix: 상세페이지 수정 1차

- src/OrderLogList/mocks/Bugs.ts
- src/OrderLogList/mocks/types/bugs.ts
- src/UserEtc/components/UserEtc.tsx
- src/UserProfile/components/UserMain.tsx
- src/core/mocks/datas/bugHistory.ts
- src/core/types/BugHistory.ts
- close #341
상점페이지 통로 뚫기 (마이페이지 지갑, etc 항목 추가)
구매내역 버그 수정 2차(제발 돼라)
> feat: 마이페이지 수정 2차

- src/RoomDetail/components/CertificationBottomSheet.tsx
- src/RoomDetail/components/RoomMember.tsx
- src/RoomDetail/components/RoomRoutine.tsx
- close #이슈번호
- 인증 버튼 열어두기
- 콕 찌르기 후 리패칭 - 아직 확인 못함...
> fix: 이미지 인증을 위한 준비

- src/RoomSetting/hooks/useRoomForm.ts
- src/RoomSetting/tabs/MemberTab/DelegationButton.tsx
- src/RoomSetting/tabs/MemberTab/KickButton.tsx
- src/RoomSetting/tabs/MemberTab/index.tsx
- src/RoomSetting/tabs/RemoveTab.tsx
- src/core/api/functions/roomAPI.ts
- src/core/mocks/datas/room.ts
- src/core/mocks/handlers/rooms.ts
- src/core/types/Room.ts
- src/pages/RoomSettingPage.tsx
- close #349 
- 방장에 대한 추방 및 위임 버튼 숨기기
- 방장 위임 API 변동 사항 반영
- deprecated된 방 삭제 탭 주석 처리 (혹시 몰라서 삭제는 안했어요)
- 방에 대한 Mutation이 동작하면 쿼리 무효화
> feat: 방 수정 페이지 QA

- src/LogList/components/LogList.tsx
- src/MyBird/components/ProductSheet.tsx
- src/MyCoupon/components/MyCouponList.tsx
- src/OrderLogList/components/OrderLogList.tsx
- src/core/api/functions/itemAPI.ts
- close #351
1. 세진님 페이지랑 동일한 ui 로 예외처리 했습니다.
2. purchase api 변경사항 반영
3. 사용내역 페이지 api 변경사항 반영
> feat: api 변경사항 반영

- src/RoomDetail/components/CertificationBottomSheet.tsx
- src/core/mocks/handlers/rooms.ts
> feat: 전송 파일 형태 변경

- src/RoomDetail/components/CertificationBottomSheet.tsx
> fix: 전송 파일 형태 변경

- src/RoomDetail/components/CertificationBottomSheet.tsx
> fix: 사진 인증 타입 수정

- src/RoomDetail/components/CertificationBottomSheet.tsx
> fix: formdata 수정

- src/pages/StartPage.tsx
- close #345
https://github.com/team-moabam/moabam-FE/assets/62418379/c540df18-fee5-4229-b101-c303349ae8e1
시작페이지에서 잠깐 화면이 덜컹거리면서
오브젝트들이 이상하게 나오는 현상을 fade-in + deffer 를 줘서 개선했습니다
> feat: 시작페이지 fade in 추가

- src/RoomDetail/components/CertificationBottomSheet.tsx
> fix: 이미지 전송 로직 수정

- src/RoomDetail/components/RoomMember.tsx
> fix: 토스트 에러 메세지 수정

- src/RoomDetail/components/RoomMember.tsx
- close #374
- 알람 에러 메세지 테스트 중
> fix: 알람 에러 메세지 테스트 중

- src/RoomDetail/components/RoomWorkspace.tsx
- src/RoomLog/components/RoomLogItem.tsx
- src/core/mocks/datas/room.ts
- src/core/types/Member.ts
- close #388 
- 인증 사진 관련 오류 수정
> fix: 인증 사진 후 리로드때 발생하는 오류 수정

- src/RoomDetail/components/RoomWorkspace.tsx
- close #388 
- certificationImage null인 경우 수 추가
> chore: certificationImage null인 경우 수 추가

- public/firebase-messaging-sw.js
- src/main.tsx
- close #389 
- Push Notification 클릭 시 기존의 스크린 활용
> feat: Push Notification 클릭 시 기존의 스크린 활용

- src/RoomSetting/hooks/useRoomForm.ts
- src/RoomSetting/tabs/RoomTab.tsx
- src/core/api/functions/roomAPI.ts
> refactor: 루틴 수정 불가능하도록 주석 처리

- src/RoomSetting/hooks/useRoomForm.ts
- close #415 
- 방 수정시 방 상세로 페이지로 이동
> refactor: 방 수정시 방 상세로 페이지로 이동

- src/core/utils/firebase.ts
- src/main.tsx
- close #387 
- Firebase 앱 초기화 로직을 함수로 래핑
> fix: Firebase 앱 초기화 로직을 함수로 래핑

- src/RoomNavigate/components/RoomNavigate.tsx
- src/RoomNavigate/utils/pickRoom.ts
- close #434 
- 아무 방에도 참여하지 않을 시 Navigation 오류 수정
> fix: 아무 방에도 참여하지 않을 시 Navigation 오류 수정

- src/core/api/functions/memberAPI.ts
- src/core/mocks/handlers/members.ts
- src/pages/JoinKakaoPage.tsx
- close #436 
- 변경된 isSignUp 필드 이름 대응
> fix: 변경된 isSignUp 필드 이름 대응

- src/App.tsx
- src/RoomNew/steps/SummaryStep.tsx
- src/core/styles/scrollbar.css
- src/main.css
- close #429 
- 방 생성시 75% 설명 추가
- 스크롤 바 변경
> feat: 방 생성시 75% 설명 추가, 스크롤 바 변경

- src/RoomDetail/components/RoomDetailContainer.tsx
- src/RoomDetail/components/RoomHeader.tsx
- src/RoomDetail/components/RoomInfo.tsx
- src/RoomDetail/components/RoomMember.tsx
- src/RoomDetail/components/RoomMemberRank.tsx
- src/RoomDetail/components/RoomMembers.tsx
- src/RoomDetail/components/RoomSemi.tsx
- src/RoomDetail/components/RoomWorkspace.tsx
- src/RoomLog/components/RoomLogItem.tsx
- src/core/mocks/datas/room.ts
- src/core/types/Room.ts
- src/pages/RoomLogPage.tsx
- src/shared/Avatar/Avatar.stories.ts
- src/shared/Avatar/Avatar.tsx
- src/shared/Avatar/Profile.tsx
- src/shared/Icon/constants/icons.ts
> fix : room detail, log 페이지 UI 수정

- src/RoomDetail/components/RoomMemberRank.tsx
- src/RoomDetail/components/RoomNotice.tsx
- src/RoomDetail/components/RoomSemi.tsx
- src/RoomDetail/components/RoomWorkspace.tsx
- src/core/mocks/datas/room.ts
> design: 상세페이지 새 이미지 사이즈 정리

- index.html
- vite.config.ts
- close #442 
- theme_color 변경
> chore: theme_color 변경

- src/RoomDetail/components/RoomDetailContainer.tsx
- src/RoomDetail/components/RoomInfo.tsx
- src/RoomDetail/components/RoomMemberRank.tsx
- src/RoomDetail/components/RoomNotice.tsx
- src/RoomDetail/components/RoomSemi.tsx
- src/core/mocks/datas/room.ts
- src/core/utils/getTimeRange.ts
- close #440
- 방 상세 공지 수정했습니다 (나연님 원래 방식대로 ref 넣었어요)
- 다크모드일때 방 배경 쫌 어둡게 했습니다
- 낮에 부엉이방이 자고있고, 밤에 오목눈이 방이 자고있게 했습니다
> feat: 방 상세 공지 및 방 배경 수정

- src/RoomDetail/components/RoomPreviewRoutine.tsx
- src/RoomDetail/components/RoomRoutine.tsx
- src/RoomDetail/components/RoomSemi.tsx
- src/RoomDetail/components/RoomWorkspace.tsx
- src/RoomDetail/utils/makeWeekCalendar.ts
- src/core/mocks/datas/room.ts
- src/core/mocks/handlers/rooms.ts
- src/pages/RoomDetailPage.tsx
> fix : 시간 인증 오류 수정

- src/RoomDetail/components/RoomRoutine.tsx
> fix: 인증 버튼 에러 수정

- .env.example
- .github/workflows/deploy_dev.yml
- .github/workflows/deploy_prod.yml
- src/core/api/instance.ts
- src/core/mocks/baseURL.ts
- close #457 
운영서버, 배포서버 환경변수 분기 처리
> chore: 운영서버, 배포서버 환경변수 분기 처리

- .github/workflows/pull_request.yml
- src/core/api/instance.ts
- src/core/constants/endpoints.ts
- src/core/mocks/baseURL.ts
- src/pages/JoinPage.tsx
- close #461 
- 프로덕션 서버에 로그인 redirect가 undefined이던 버그 수정
- 백엔드 API, 클라이언트 배포경로를 하나의 상수파일에서 관리
- push 빌드 테스트에 dev 브랜치 추가
> fix: 프로덕션 서버의 로그인 redirect 경로에 undefined 오류

- src/StoreList/components/StoreList.tsx
- close #477 
- 프로덕션 배포에 결제 기능 임시 제한
> fix: 프로덕션 배포에 결제 기능 임시 제한

- src/RoomDetail/components/RoomRoutine.tsx
- close #486 
인증 성공 실패 여부 상태 보여주기
> fix: 인증 성공 실패 여부 상태 보여주기

- src/domain/RoomDetail/components/RoomDetail.tsx
- src/domain/RoomDetail/components/RoomDetailContainer.tsx
- src/domain/RoomDetail/components/RoomWorkspace.tsx
- close #496
한자리수 달일 경우, API 요청에서 에러가 나는 부분을 수정했습니다
(2024-1-03 -> 2024-01-03)
> fix: 한자리수 날짜 버그 수정
